spring.application.name=messenger

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.url=${DB_URL_MESSENGER_APP}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.websocket.allowed-origin-patterns=http://localhost:*
